# Generated by Django 4.1.1 on 2022-10-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_statuscrm_alter_order_order_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComentCrm',
        ),
    ]
